name: ALL Build (Linux, macOS, Windows, Android, IPA, APK, AAB)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  # بناء لجميع المنصات
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        android: [true]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5 python-vlc

      - name: Build Executable for ${{ matrix.os }}
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller --onefile main.py
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller --onefile main.py
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            pyinstaller --onefile main.py
          fi

      - name: Upload Executable for ${{ matrix.os }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/

  # بناء APK & AAB للأندرويد
  android:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK for Android
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y android-sdk

      - name: Install dependencies for Android
        run: |
          pip install buildozer
          sudo apt-get install -y python3-dev build-essential libssl-dev libffi-dev python3-setuptools

      - name: Build APK & AAB for Android
        run: |
          buildozer android debug
          buildozer android release

      - name: Upload APK & AAB
        uses: actions/upload-artifact@v3
        with:
          name: android-builds
          path: bin/

  # بناء IPA للأجهزة الخاصة بـ Apple (macOS)
  ios:
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout c
